main.plugins.display-password.enabled = true
main.plugins.display-password.orientation = "horizontal"
main.plugins.display-password.h_pos_x = 0
main.plugins.display-password.h_pos_y = 91
main.plugins.display-password.v_pos_x = 180
main.plugins.display-password.v_pos_y = 61
